trigger: none

parameters:
  - name: VM
    displayName: VM Agent Operating System
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest
  - name: hascommit
resources:
  repositories:
  - repository: githubrepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: lmartinezs
    name: lmartinezs/github-actions
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  PRE_RELEASE: new_one

stages:
  - stage: build
    pool:
      vmImage: ${{ parameters.VM }}
    jobs:
      - job: build
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        #- checkout: githubrepo
        - script: |
            gh auth login --with-token
            if [[ $(gh release list | grep -E 'Draft|Pre-release' | wc -l) -ne 0 ]]; then
              echo "There is an open Pre-release"
              PRE_RELEASE=current_one
              PRE_RELEASE_BRANCH=rc/$(gh release list | grep -E 'Pre-release' | awk -F' ' '{print $1}')
              echo "PRE_RELEASE_BRANCH=$(PRE_RELEASE_BRANCH)" >> $GITHUB_ENV
              LATEST_PRERELEASE_TAG=$(gh release list | grep -E 'Pre-release' | awk -F' ' '{print $3}')
              echo "Current Pre-release: $LATEST_PRERELEASE_TAG in branch $PRE_RELEASE_BRANCH"
            else
              PRE_RELEASE=new_one
            fi
            #echo "PRE_RELEASE=$PRE_RELEASE"  >> $GITHUB_ENV
            echo "##vso[task.setvariable variable=PRE_RELEASE]$PRE_RELEASE"
            echo $PRE_RELEASE
          displayName: Check open pre-release
          env:
            GH_TOKEN: $(gh.token)

        - script: | 
            echo $(GIT_COMMIT)
            echo $(GIT_BRANCH)
            echo $(PRE_RELEASE)

          displayName: 'Run a multi-line script'