trigger: none

parameters:
  - name: VM
    displayName: VM Agent Operating System
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest
  - name: hascommit
resources:
  repositories:
  - repository: githubrepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: lmartinezs
    name: lmartinezs/github-actions
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

stages:
  - stage: build
    pool:
      vmImage: ${{ parameters.VM }}
    jobs:
      - job: build
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        #- checkout: githubrepo

        - script: | 
            echo $(GIT_COMMIT)
            echo $(GIT_BRANCH)
          displayName: 'Run a multi-line script'