trigger: none

parameters:
  - name: VM
    displayName: VM Agent Operating System
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - windows-latest
  - name: hascommit


stages:
  - stage: build
    pool:
      vmImage: ${{ parameters.VM }}
    jobs:
      - job: build
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'