name: On pull request

on:
  pull_request_target:
    branches:    
      - 'master'
      - 'production'
jobs:
  master:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: echo "to master"
  prod:
    if: github.base_ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: echo "to production"
