name: Publish to production

on:
  push:
    branches:
      - master
jobs:
  pushtoprod:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Checkout latest release tag
      run: |
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          echo "LATEST_TAG=${LATEST_TAG}"
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Gen dummy page
      run: |
            mkdir public
            cat > public/index.html <<EOL
            <!doctype html>
            <html>
              <head>
                <title>GitHub Pages deployed!</title>
              </head>
              <body>
                <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
              </body>
            </html>
            EOL
    - name: Gen dummy page
      run: |
             cat public/index.html >> $GITHUB_STEP_SUMMARY
      
