name: Publish release to production
on:
  release:
    types: [released]

jobs:
  release:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
    - run: echo "release created on ${{ github.repository }} repository" 
