name: Publish-Release
on:
  push:
jobs:
  MyRun:
    runs-on: ubuntu-latest
    continue-on-error: true    
    steps:
      - name: Step One
        if: ${{ always() }}
        run: curl --fail -o dates.csv https://doesnotexist.com/dates.csv
      - name: Step Two
        run: date >> dates.csv
  MyRun2:
    runs-on: ubuntu-latest    
    steps:
      - name: Step One
        run: echo "success"
      
